project 'OhEuropa.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OhEuropa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OhEuropa
  pod 'ReachabilitySwift'
  pod 'GoogleMaps', '~> 2.5'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'StreamingKit'
  pod 'TweenKit'
  pod "ProcessingKit"
  pod 'FontAwesome.swift'
  pod 'Sync', '~> 4'
  
  target 'OhEuropaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OhEuropaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
